name: Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    strategy:
      matrix:
        goos: [ linux, darwin, windows ]
        goarch: [ amd64, arm64 ]
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux


    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.24
          binary_name: "geocn"
          extra_files: README.md
      - name: Build and Push Multi-Arch Docker Image
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            luola/geocn-go:latest
            luola/geocn-go:${{ github.ref_name }}
          cache-from: type=registry,ref=luola/geocn-go:cache
          cache-to: type=inline
      - name: Upload Release Asset (Binary)
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        uses: softprops/action-gh-release@v1
        with:
          files: geocn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}